### ISSUE TITLE
.npy file construction

### ISSUE THREAD

**Issue by 1029734570** [Derek-Wds/PoGeVon#2]
Hello, I would like to ask how the `adjacency_point.npy` and `adjacency_point.npy` files in the dataset folder are constructed.

**Comment by Derek-Wds** [comment]
Please refer to the  Section 4.1 of our paper for more information. It should be a relatively simple process for generating a similar dataset. Hope this helps.

**Comment by 1029734570** [comment]
![1](https://github.com/user-attachments/assets/b2e9c020-60f4-434d-97d8-b13ef1e29b0c)
![image](https://github.com/user-attachments/assets/dc5da1a4-800a-4f18-86e5-3f0e88e2ca3f)
I'm very happy that you replied to me, thank you very much. After re-reading section 4.1 and comparing it with the code you provided, I want to ask if the adjacency matrix for pems04 was constructed using the part of the code I highlighted. If so, given that the dimensions of the adjacency_point file are (25920, 64, 64) instead of (64, 64), are you initializing the adjacency matrix for each timestamp with the adjacency matrix calculated by the code? Also, could you explain the difference between the adjacency_point_label file and the adjacency_point file? Looking forward to your reply
